media: assets

content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    view:
      fields: [ title, author, date, draft ]
      sort: [ title, author, date, draft ]
    fields:
      - {name: title, label: Title, type: string}
      - {name: subtitle, label: Subtitle, type: string}
      - {name: date, label: Date, type: date}
      - {name: lastmod, label: Last Modified, type: date}
      - {name: draft, label: Draft, type: boolean, default: true}
      - {name: hiddenFromHomePage, label: Hidden from home page, type: boolean, default: false, hidden: false}
      - {name: hiddenFromSearch, label: Hidden from site search, type: boolean, default: false, hidden: false}
      - name: tags
        label: Tags
        type: select
        options:
          multiple: true
          values: [ tag1, tag2, tag3]
          creatable: true
      - name: categories
        label: Categories
        type: select
        options:
          multiple: true
          values: [ cat1, cat2, cat3 ]
          creatable: true
      - {name: author, label: Author, type: string}
      - {name: description, label: Description, type: string, options: ( maxlength: 160 ) }
      - {name: image, label: Image, type: image}
      - {name: body, label: Body, type: rich-text}
      - {name: lightgallery, label: Light Gallery, type: boolean, default: true, hidden: true}
      - {name: fontawesome, label: Font Awesome, type: boolean, default: true, hidden: true}
      
  - name: projects
    label: Projects
    type: collection
    path: content/projects
    view:
      fields: [ title, author, date, draft ]
      sort: [ title, author, date, draft ]
    fields:
      - {name: title, label: Title, type: string}
      - {name: subtitle, label: Subtitle, type: string}
      - {name: date, label: Date, type: date}
      - {name: lastmod, label: Last Modified, type: date}
      - {name: draft, label: Draft, type: boolean, default: true}
      - {name: hiddenFromHomePage, label: Hidden from home page, type: boolean, default: false, hidden: false}
      - {name: hiddenFromSearch, label: Hidden from site search, type: boolean, default: false, hidden: false}
      - name: tags
        label: Tags
        type: select
        options:
          multiple: true
          values: [ tag1, tag2, tag3]
          creatable: true
      - name: categories
        label: Categories
        type: select
        options:
          multiple: true
          values: [ cat1, cat2, cat3 ]
          creatable: true
      - {name: author, label: Author, type: string}
      - {name: description, label: Description, type: string, options: ( maxlength: 160 ) }
      - {name: image, label: Image, type: image}
      - {name: body, label: Body, type: rich-text}
      - {name: lightgallery, label: Light Gallery, type: boolean, default: true, hidden: true}
      - {name: fontawesome, label: Font Awesome, type: boolean, default: true, hidden: true}
      
  - name: about
    label: About
    type: file
    path: content/about.md
    fields:
      - {name: draft, label: Draft, type: boolean, default: false}
      - {name: lastmod, label: Last Modified, type: date}
      - {name: image, label: Image, type: image}
      - {name: body, label: Body, type: rich-text}
      - {name: lightgallery, label: Light Gallery, type: boolean, default: true, hidden: true}
      - {name: fontawesome, label: Font Awesome, type: boolean, default: true, hidden: true}